name: Release Binary
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: biomon-${{ matrix.target }}.exe
          path: target/${{ matrix.target }}/release/biomon.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: biomon-${{ matrix.target }}.exe
          path: .
      
      - name: List
        run: ls -alh /home/runner/work/biomon/biomon

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: /home/runner/work/biomon/biomon/biomon.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  